# Generated by Django 4.2 on 2023-07-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotionApp', '0002_product_price_currency_alter_category_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='promotionApp.product'),
        ),
    ]
