# Generated by Django 4.2 on 2023-07-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotionApp', '0005_alter_promotion_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
    ]
