# Generated by Django 4.2 on 2023-07-16 18:51

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promotionApp', '0009_alter_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', max_digits=4, null=True),
        ),
    ]
