# Generated by Django 4.2 on 2023-11-10 17:52

from django.db import migrations, models
import promotionApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotionApp', '0013_remove_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[promotionApp.models._validate_image_size, promotionApp.models._validate_image_extension]),
        ),
    ]
